#!/usr/bin/env sh
#
# NAME
#   bootstrap — bootstrap the project for local development
#
# vim: set ts=4 sw=4 sts=4 noet:
set -e
if test -n "$CI_DEBUG_TRACE" -o -n "$SHELLDEBUG"
then
	set -x
fi
just bootstrap
