name: Deployment
on:
  push:
    branches-ignore: ["*"]
    tags: ["*"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'gmr/pgparse' && startsWith(github.event.ref, 'refs/tags')
    container: python:3.9-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup environment
        run: apk --update add gcc git libexecinfo-dev make musl-dev protoc

      - name: Install Cython
        run: pip3 install cython

      - name: Bootstrap the project
        run: ./bootstrap

      - name: Build extension
        run: USE_CYTHON=1 python3 setup.py build_ext --force --inplace

      - name: Build proto file
        run: USE_PROTOC=1 python3 setup.py build_py --force

      - name: Build package
        run: python3 setup.py sdist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
