name: Testing
on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'docs/**'
      - 'setup.*'
      - '*.md'
      - '*.rst'
    tags-ignore: ["*"]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8]
    container:
      image: python:${{ matrix.python }}-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup environment
        run: apk --update add bzip2 ca-certificates cyrus-sasl icu-libs libedit libffi libintl openssl perl tzdata asciidoc autoconf automake bison bzip2 clang cmake coreutils cyrus-sasl-dev expat-dev flex curl gcc g++ gdbm gettext-dev git icu-dev libc-dev libedit-dev libffi-dev libxml2-dev libxslt-dev libtool linux-headers llvm8-dev make musl-dev openssl-dev perl-dev python3-dev unzip util-linux-dev xmlto zlib-dev

      - name: Bootstrap the project
        run: ./bootstrap

      - name: Install testing dependencies
        run: pip3 install -r requires/testing.txt

      - name: Run tests
        run: ci/test.sh

      - name: Upload Coverage
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: build/coverage.xml
