name: Testing
on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'docs/**'
      - 'setup.*'
      - '*.md'
      - '*.rst'
    tags-ignore: ["*"]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    container:
      image: python:${{ matrix.python }}-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup environment
        run: apk --update add gcc git libexecinfo-dev make musl-dev protoc

      - name: Bootstrap the project
        run: ./bootstrap

      - name: Install testing dependencies
        run: pip3 install -r requires/testing.txt

      - name: Run tests
        run: ci/test.sh

      - name: Upload Coverage
        uses: codecov/codecov-action@v1.0.2
        if: github.event_name == 'push' && github.repository == 'gmr/pgparse'
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: build/coverage.xml
